# Generates kytyCodegenVersion.h for the persistent program cache (KYTY_PROGRAM_CACHE,
# graphics/shader/recompiler/CodegenFingerprint.h):
# - KYTY_CODEGEN_VERSION: SHA-256 over every file of the codegen source set (relative path and
#   content hash), this script, and the compiler identity and flags. Cache files written by a build
#   with another version are not used.
# - KYTY_CODEGEN_SWITCH_LIST: every "KYTY_*" string literal in those files (the environment
#   switches the codegen fingerprint records), except the program cache's own switches.
# The build fails when a file of the set includes a project header that is neither in the set nor
# exempt below: the version would not see changes to it. Exempt headers cannot change what a
# translation produces, or the fingerprint records the values they contribute (rendererBatch.h:
# KYTY_RENDERER_BATCH; bufferCache.h: CACHING_PAGEBITS/CACHING_PAGESIZE).
#
# Inputs: SOURCE_ROOT (src), FILE_LIST (absolute paths, one per line), OUTPUT_FILE, COMPILER.

set(exempt_patterns
	"^common/"
	"^graphics/host_gpu/renderer/cache/bufferCache\\.h$"
	"^kytyCodegenVersion\\.h$"
)

file(STRINGS "${FILE_LIST}" files)
list(REMOVE_DUPLICATES files)
list(SORT files)

set(members "")
foreach(path IN LISTS files)
	file(RELATIVE_PATH relative "${SOURCE_ROOT}" "${path}")
	list(APPEND members "${relative}")
endforeach()

set(manifest "")
set(switches "")
file(READ "${SOURCE_ROOT}/graphics/shader/recompiler/CodegenFingerprint.cpp" fingerprint_source)
foreach(path IN LISTS files)
	file(RELATIVE_PATH relative "${SOURCE_ROOT}" "${path}")
	file(SHA256 "${path}" digest)
	string(APPEND manifest "${relative} ${digest}\n")
	file(READ "${path}" content)
	# Host device state the emitter reads (Spirv::SetHost*, set by the device layer): every such
	# setter must have its getter in the codegen fingerprint.
	string(REGEX MATCHALL "void[ \t]+SetHost[A-Za-z0-9_]+[ \t]*\\(" setters "${content}")
	foreach(setter IN LISTS setters)
		string(REGEX REPLACE "void[ \t]+SetHost([A-Za-z0-9_]+).*" "\\1" state "${setter}")
		if(NOT fingerprint_source MATCHES "GetHost${state}\\(")
			message(FATAL_ERROR "codegen_version.cmake: ${relative} declares SetHost${state}, but "
			                    "recompiler/CodegenFingerprint.cpp does not record GetHost${state}(): "
			                    "add it to CodegenFingerprint().")
		endif()
	endforeach()
	string(REGEX MATCHALL "\"KYTY_[A-Z0-9_]+\"" names "${content}")
	foreach(name IN LISTS names)
		string(REPLACE "\"" "" name "${name}")
		if(NOT name MATCHES "^KYTY_PROGRAM_CACHE")
			list(APPEND switches "${name}")
		endif()
	endforeach()
	get_filename_component(directory "${path}" DIRECTORY)
	string(REGEX MATCHALL "#[ \t]*include[ \t]*\"[^\"]+\"" includes "${content}")
	foreach(include IN LISTS includes)
		string(REGEX REPLACE "#[ \t]*include[ \t]*\"([^\"]+)\"" "\\1" include "${include}")
		set(target "${include}")
		if(NOT EXISTS "${SOURCE_ROOT}/${include}" AND EXISTS "${directory}/${include}")
			file(RELATIVE_PATH target "${SOURCE_ROOT}" "${directory}/${include}")
		endif()
		list(FIND members "${target}" member)
		if(member GREATER_EQUAL 0)
			continue()
		endif()
		set(exempt FALSE)
		foreach(pattern IN LISTS exempt_patterns)
			if(target MATCHES "${pattern}")
				set(exempt TRUE)
			endif()
		endforeach()
		if(NOT exempt)
			message(FATAL_ERROR "codegen_version.cmake: ${relative} includes \"${include}\", which is "
			                    "outside the codegen source set. Add it to kyty_codegen_sources in "
			                    "CMakeLists.txt, or (if it cannot change what a translation produces) to "
			                    "the exemptions in src/codegen_version.cmake.")
		endif()
	endforeach()
endforeach()
list(REMOVE_DUPLICATES switches)
list(SORT switches)

file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" script_digest)
string(SHA256 version "${manifest}script ${script_digest}\ncompiler ${COMPILER}\nswitches ${switches}\n")
list(LENGTH files file_count)

set(switch_list "")
foreach(name IN LISTS switches)
	string(APPEND switch_list "\"${name}\", ")
endforeach()

set(header "// Generated by src/codegen_version.cmake from ${file_count} codegen source files; do not edit.\n")
string(APPEND header "#pragma once\n")
string(APPEND header "#define KYTY_CODEGEN_VERSION \"${version}\"\n")
string(APPEND header "#define KYTY_CODEGEN_FILE_COUNT ${file_count}\n")
string(APPEND header "#define KYTY_CODEGEN_SWITCH_LIST ${switch_list}\n")
file(WRITE "${OUTPUT_FILE}" "${header}")
# The file list with digests, for inspecting what a version covers.
file(WRITE "${OUTPUT_FILE}.manifest.txt" "${manifest}compiler ${COMPILER}\nversion ${version}\n")
